sudo: false
language: java

env:
   global:
    - BEAM_VERSION="2.11.0"
    - MAVEN_OPTS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"

before_cache:
  - rm -Rf $HOME/.m2/repository/org/talend/sdk/component
  - find $HOME/.m2/repository/ -name *SNAPSHOT | xargs rm -Rf

cache:
  timeout: 1000
  directories:
  - "$HOME/.m2"

script:
  - git clone --depth 1 https://github.com/Talend/component-runtime
  - cd component-runtime
  - travis_wait 50 mvn install -B -am -pl 'component-runtime-beam' -Dbeam.version=$BEAM_VERSION
