sudo: false
language: java
env:
  global:
  - BEAM_VERSION="2.13.0-SNAPSHOT"
  - MAVEN_OPTS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"
before_cache:
- rm -Rf $HOME/.m2/repository/org/talend/sdk/component
- find $HOME/.m2/repository/ -name *SNAPSHOT | xargs rm -Rf
cache:
  directories:
  - "$HOME/.m2"
script:
- git clone --depth 1 https://github.com/Talend/component-runtime
- cd component-runtime
- travis_wait 50 mvn install -B -am -pl 'component-runtime-beam' -Dbeam.version=$BEAM_VERSION
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms: 
      secure: j3YYBFq1Jd8vTd98Om8U74ueDiVq71o4kg09ro1k/gKO5XCUzz/s3Ab8OtYLUXV43asXRQbA0mENKOk0m7Og2M+R8+xdHTrwbXbO1NI4nBOr2qPK50nVh9tTOj5vKBWANzYwO6FRTQo3/86qWC8GeomatVHl6mXIm4YaTuQXwXpe9Nr17gu1dybOZU4Mffq/NyqKTd3LU6lLyk4zvnq7hykONz+tgF/5ulC7lB2ztEkqxPhjwSvxTizJpZTORJOihNxPHezgRiF7RVHuN8njPNYa8EhsXLUUdr13QCI4xBjZ9GeutHl7QdvkCeBvEYsmfFltRbJ/kuHEs3Rg4edmUUMOzUlggJEk9uQW972uyKmaSVdG98G7O/0L4JTn/X0VQHEKslrKm4sier5ROZ+ZLwx9FTEuM80E2D518sK4nrWLX5HD5mHUGF/gU1NwaZr2cN3+4IySX9UkOjvazab2oSyPSAQkc2BFqPqNTTVS77R1pb/J/L3kw5YCxUGvRMoUXvCR/M2Dq4LCYi60NKM+IGHqPpzMMTp9zyQwzxW3W0jJXDq19HsoY2hQ8Z3DgI7aUOTzorxpwbiSR1cga3MRMwjxokGUSr/8AzQRnvXvbzSc0uBgEgjS6Yr3jjBSoYHCdlBeq6ntMRxjH9zLo9ZxeHhzFQ0e9DT0YR67/A82lYE=
