name: Docker CI
on:
  push:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BEAM_VERSION:
          - 2.19.0
          - 2.20.0-SNAPSHOT
      fail-fast: false
    steps:
      - name: Checkout Talend/component-runtime-beam-test-snapshots
        uses: actions/checkout@v2
      - name: Run docker image
        run:
          docker build --build-arg BEAM_VERSION=${{ matrix.BEAM_VERSION }} -t components-runtime-beam-snapshots-test .
