name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag components-runtime-beam-snapshots-test:$(date +%s)
      env:
        BEAM_VERSION: 2.19.0-SNAPSHOT
